# Generated by Django 3.1.8 on 2022-10-20 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_trials', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('session_completed', models.BooleanField(default=False)),
                ('questionnaire_completed', models.BooleanField(default=False)),
                ('task_completed', models.BooleanField(default=False)),
                ('tutorial_completed', models.BooleanField(default=False)),
                ('conditioning_completed', models.BooleanField(default=False)),
                ('total_reward', models.IntegerField(default=0)),
                ('total_payment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_issued', models.BooleanField(default=False)),
                ('final_performance', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('payment_token', models.CharField(max_length=40)),
                ('external_study_ID', models.CharField(default='', max_length=100)),
                ('external_session_ID', models.CharField(default='', max_length=100)),
                ('strategy', models.CharField(default='', max_length=1000)),
                ('strategy_radio', models.CharField(default='', max_length=30)),
                ('perceived_difficulty', models.CharField(default='', max_length=10)),
                ('conditioning_attributes', models.JSONField(default=list)),
                ('generalization_attributes', models.JSONField(default=list)),
                ('set_1_attribute', models.JSONField(default=list)),
                ('set_2_attribute', models.JSONField(default=list)),
                ('task', models.CharField(default='', max_length=100)),
                ('key_conversion', models.JSONField(default=dict)),
                ('substances', models.JSONField(blank=True, default=list, null=True)),
                ('passed_attention_check', models.BooleanField(default=True)),
                ('project', models.CharField(default='initial', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=64)),
                ('shape', models.CharField(max_length=64)),
                ('texture', models.CharField(max_length=64)),
                ('size', models.CharField(default='', max_length=64)),
                ('reward_probabilities', models.JSONField(default=dict)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ID', models.CharField(max_length=64)),
                ('external_source', models.CharField(max_length=64)),
                ('age', models.CharField(max_length=20)),
                ('sex', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=20)),
                ('is_bot', models.BooleanField(default=False)),
                ('psych_history', models.JSONField(blank=True, default=list, null=True)),
                ('prolific_reported_psych_history', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaceship', models.CharField(max_length=64)),
                ('setting', models.CharField(max_length=64)),
                ('reward_probabilities', models.JSONField(default=dict)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=2)),
                ('reward', models.BooleanField(null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('block', models.CharField(max_length=20)),
                ('reward_probs_record', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='alienartifacts.session')),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='alienartifacts.stimulus')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='alienartifacts.subject'),
        ),
        migrations.CreateModel(
            name='QuestionnaireQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_name', models.CharField(max_length=100)),
                ('subscale', models.CharField(blank=True, max_length=40, null=True)),
                ('possible_answers', models.JSONField(default=dict)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.IntegerField()),
                ('questionnaire_question_number', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_q', to='alienartifacts.session')),
            ],
        ),
    ]
