# Generated by Django 3.1.8 on 2022-10-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alienartifacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='prolific_reported_psych_history',
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('task', models.CharField(default='', max_length=100)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('source', models.CharField(default='', max_length=100)),
                ('accepted', models.BooleanField(default=None, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='alienartifacts.subject')),
            ],
        ),
    ]
