# Generated by Django 3.1.8 on 2022-10-22 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alienartifacts', '0002_auto_20221022_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='prolific_study_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='alienartifacts.session'),
        ),
    ]
