# Generated by Django 3.1.8 on 2022-10-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alienartifacts', '0003_auto_20221022_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='temp_field',
            field=models.CharField(default='', max_length=100),
        ),
    ]
