# Generated by Django 3.1.8 on 2022-10-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alienartifacts', '0004_recruitment_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='temp_field',
        ),
    ]
