# Generated by Django 3.1.8 on 2022-11-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alienartifacts', '0005_remove_recruitment_temp_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireq',
            name='subscale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
