# Generated by Django 3.1.8 on 2022-11-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alienartifacts', '0006_auto_20221106_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='block',
            field=models.CharField(max_length=100),
        ),
    ]
