# Generated by Django 3.1.8 on 2022-12-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alienartifacts', '0007_auto_20221109_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='age_numeric',
            field=models.IntegerField(default=0),
        ),
    ]
