# Generated by Django 3.1.8 on 2022-12-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alienartifacts', '0008_subject_age_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='confidence_key_conversion',
            field=models.JSONField(default=dict),
        ),
    ]
