# Generated by Django 3.1.8 on 2022-12-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alienartifacts', '0009_session_confidence_key_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='confidence',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
